### ISSUE TITLE
Beautiful theme

### ISSUE THREAD

**Issue by spences10** [rwwagner90/hyper-adventure-time#1]
Love the theme, thank you ✨🚀🦄

I'd like to know how you styled the 'powerline'? so it show the nice point and ligatures?

This bit: 
![image](https://user-images.githubusercontent.com/234708/30700191-cbf4afce-9ede-11e7-8632-3ded16f9ef80.png)

I know it's not relating to your theme, I just like the look of it and would like to know how to apply it to my terminal

Thanks again

**Comment by RobbieTheWagner** [comment]
Hi @spences10 that is powerline, which I think I used http://khanh-ng.blogspot.com/2015/02/install-powerline-for-mac-os-x.html to somewhat tell me how to install it, but it is finicky. I suggest looking up powerline for your OS of choice and finding some good instructions on how to install it 😄

**Comment by spences10** [comment]
@rwwagner90 thanks for the pointer 👍 

And the awesome theme 😄
